### PR TITLE
Pushbullet notifications

### PR DESCRIPTION
**Pull request by soxidus**
I Implemented Notifications to also work with pushbullet

 - So Far they are just send via Broadcast to all devices listening on your account 
 - the Title of the push is Hardcoded as "DASH-BUTTON"

feature should work as is

### CODE REVIEW

**Comment by Nekmo** [comment]
Hi! Thanks for your PR.

I need a little time to do pushbullet tests. If you have time you can write unittests for this new feature. The amazon-dash project has a very high coverage because all the code has tests.

Thanks again for your contribution. This new feature will be included in Amazon-dash 1.3.0. The code will also be used for THEN project.

https://github.com/Nekmo/then/issues/28

Amazon-dash 2.0 will use the THEN project.

**Comment by Nekmo** [comment]
Pushbullet requirement can be eliminated.

**Comment by Nekmo** [comment]
This pull request has been rejected for the following reasons:

- It includes an unnecessary requirement (``pushbullet.py``)
- The source code does not pass the PEP8
- The component does not include the target option available in the API: https://docs.pushbullet.com/#create-push
- This pull request does not include documentation
- This pull request does not include tests

All contributions are welcome but it is necessary to respect quality standards. 

Sorry for the inconvenience. I hope you can collaborate in the future.

**Comment by soxidus** [comment]
No Problem,
once I got the time i'll change the PB lib to a clean REST Call so no deps required 
hope that will pass ;)

**Comment by Nekmo** [comment]
I have made an implementation without need the external dependency. The new version will come out today. https://github.com/Nekmo/amazon-dash/issues/90

I hope it does not bother you.

Regards

**Pull request closed without merging**
