### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by bachya**
This PR adds support for hosting and running Amazon Dash within a Docker container (#61).

Below are instructions on how to correctly host a Docker image on Docker Hub going forward.

## Set up Docker
1. Install Docker in your environment: [About Docker CE | Docker Documentation](https://docs.docker.com/install/)

## Set up a Docker Hub Repo
1. Create an account at https://hub.docker.com/.
2. Click on "Create Repository".
3. Fill out the properties and create the repo.

## Create an Automated Build Process
At the Docker Hub website:

1. Click "Create" >> "Create Automated Build"
2. Link your GitHub account, then click "Create Auto-build GitHub".
3. Find and select the `nekmo/amazon-dash` repo.
4. Fill out the details and click "Create".
5. Click on "Build Settings" and set up your settings as needed. I think two rules makes sense to start, but you make the call:
	1. `Branch` – `master` – `/` – `latest`
	2. `Tag` – `<EMPTY>` – `/` – `<Same as tag>`

## Push As Normal
With the above rules, the following will occur anytime you push:

1. Any commit pushed to `master` will trigger a Docker build to the `latest` tag.
2. Any tagged commit will trigger a Docker build to the tag that matches.

---

Feel free to add me as a collaborator to this Docker repo; happy to help you maintain while you get your feet under you!

Lastly, I _think_ the docs are sufficient and correct, but let me know if more is needed.

### CODE REVIEW

**Comment by Nekmo** [comment]
Everything seems to be correct :+1: I have to check that it works on my machine and will be included in Amazon-dash 1.2.0. 

Do you want to appear in the contributors section?

**Comment by bachya** [comment]
@Nekmo Happy to join as a contributor! I can help with the Docker Hub stuff that way, too.

**Comment by Nekmo** [comment]
@bachya  It's done. Thank you :)

**Comment by bachya** [comment]
@Nekmo If you'd like me to manage the Docker Hub stuff, you'll either need me to make me a co-owner of this repo or set up the Docker Hub repo and make me a co-owner there.

**Pull request merged**
